/* 
 * Tradovate MarketData API
 *
 * Tradovate MarketData API provides an access to the complete set of Tradovate market data functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.MarketData.Services.Api;
using Tradovate.MarketData.Services.Model;
using Tradovate.MarketData.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.MarketData.Services.Test
{
    /// <summary>
    ///  Class for testing ChartTimeRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChartTimeRangeTests
    {
        // TODO uncomment below to declare an instance variable for ChartTimeRange
        //private ChartTimeRange instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChartTimeRange
            //instance = new ChartTimeRange();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChartTimeRange
        /// </summary>
        [Test]
        public void ChartTimeRangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChartTimeRange
            //Assert.IsInstanceOfType<ChartTimeRange> (instance, "variable 'instance' is a ChartTimeRange");
        }


        /// <summary>
        /// Test the property 'ClosestTimestamp'
        /// </summary>
        [Test]
        public void ClosestTimestampTest()
        {
            // TODO unit test for the property 'ClosestTimestamp'
        }
        /// <summary>
        /// Test the property 'ClosestTickId'
        /// </summary>
        [Test]
        public void ClosestTickIdTest()
        {
            // TODO unit test for the property 'ClosestTickId'
        }
        /// <summary>
        /// Test the property 'AsFarAsTimestamp'
        /// </summary>
        [Test]
        public void AsFarAsTimestampTest()
        {
            // TODO unit test for the property 'AsFarAsTimestamp'
        }
        /// <summary>
        /// Test the property 'AsMuchAsElements'
        /// </summary>
        [Test]
        public void AsMuchAsElementsTest()
        {
            // TODO unit test for the property 'AsMuchAsElements'
        }

    }

}
