/* 
 * Tradovate MarketData API
 *
 * Tradovate MarketData API provides an access to the complete set of Tradovate market data functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.MarketData.Services.Api;
using Tradovate.MarketData.Services.Model;
using Tradovate.MarketData.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.MarketData.Services.Test
{
    /// <summary>
    ///  Class for testing ChartDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChartDescriptionTests
    {
        // TODO uncomment below to declare an instance variable for ChartDescription
        //private ChartDescription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChartDescription
            //instance = new ChartDescription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChartDescription
        /// </summary>
        [Test]
        public void ChartDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChartDescription
            //Assert.IsInstanceOfType<ChartDescription> (instance, "variable 'instance' is a ChartDescription");
        }


        /// <summary>
        /// Test the property 'UnderlyingType'
        /// </summary>
        [Test]
        public void UnderlyingTypeTest()
        {
            // TODO unit test for the property 'UnderlyingType'
        }
        /// <summary>
        /// Test the property 'ElementSize'
        /// </summary>
        [Test]
        public void ElementSizeTest()
        {
            // TODO unit test for the property 'ElementSize'
        }
        /// <summary>
        /// Test the property 'ElementSizeUnit'
        /// </summary>
        [Test]
        public void ElementSizeUnitTest()
        {
            // TODO unit test for the property 'ElementSizeUnit'
        }
        /// <summary>
        /// Test the property 'ElementSize2'
        /// </summary>
        [Test]
        public void ElementSize2Test()
        {
            // TODO unit test for the property 'ElementSize2'
        }
        /// <summary>
        /// Test the property 'CustomUnderlying'
        /// </summary>
        [Test]
        public void CustomUnderlyingTest()
        {
            // TODO unit test for the property 'CustomUnderlying'
        }
        /// <summary>
        /// Test the property 'WithHistogram'
        /// </summary>
        [Test]
        public void WithHistogramTest()
        {
            // TODO unit test for the property 'WithHistogram'
        }
        /// <summary>
        /// Test the property 'CloseOnly'
        /// </summary>
        [Test]
        public void CloseOnlyTest()
        {
            // TODO unit test for the property 'CloseOnly'
        }
        /// <summary>
        /// Test the property 'Throttle'
        /// </summary>
        [Test]
        public void ThrottleTest()
        {
            // TODO unit test for the property 'Throttle'
        }

    }

}
