/* 
 * Tradovate MarketData API
 *
 * Tradovate MarketData API provides an access to the complete set of Tradovate market data functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.MarketData.Services.Api;
using Tradovate.MarketData.Services.Model;
using Tradovate.MarketData.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.MarketData.Services.Test
{
    /// <summary>
    ///  Class for testing ChartSubscriptionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChartSubscriptionResultTests
    {
        // TODO uncomment below to declare an instance variable for ChartSubscriptionResult
        //private ChartSubscriptionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChartSubscriptionResult
            //instance = new ChartSubscriptionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChartSubscriptionResult
        /// </summary>
        [Test]
        public void ChartSubscriptionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChartSubscriptionResult
            //Assert.IsInstanceOfType<ChartSubscriptionResult> (instance, "variable 'instance' is a ChartSubscriptionResult");
        }


        /// <summary>
        /// Test the property 'ErrorText'
        /// </summary>
        [Test]
        public void ErrorTextTest()
        {
            // TODO unit test for the property 'ErrorText'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'HistoricalId'
        /// </summary>
        [Test]
        public void HistoricalIdTest()
        {
            // TODO unit test for the property 'HistoricalId'
        }
        /// <summary>
        /// Test the property 'RealtimeId'
        /// </summary>
        [Test]
        public void RealtimeIdTest()
        {
            // TODO unit test for the property 'RealtimeId'
        }

    }

}
