/* 
 * Tradovate MarketData API
 *
 * Tradovate MarketData API provides an access to the complete set of Tradovate market data functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.MarketData.Services.Api;
using Tradovate.MarketData.Services.Model;
using Tradovate.MarketData.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.MarketData.Services.Test
{
    /// <summary>
    ///  Class for testing UnsubscribeDOM
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UnsubscribeDOMTests
    {
        // TODO uncomment below to declare an instance variable for UnsubscribeDOM
        //private UnsubscribeDOM instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UnsubscribeDOM
            //instance = new UnsubscribeDOM();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UnsubscribeDOM
        /// </summary>
        [Test]
        public void UnsubscribeDOMInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UnsubscribeDOM
            //Assert.IsInstanceOfType<UnsubscribeDOM> (instance, "variable 'instance' is a UnsubscribeDOM");
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

    }

}
