/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// CancelSecondMarketDataSubscription
    /// </summary>
    [DataContract]
        public partial class CancelSecondMarketDataSubscription :  IEquatable<CancelSecondMarketDataSubscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelSecondMarketDataSubscription" /> class.
        /// </summary>
        /// <param name="secondMarketDataSubscriptionId">secondMarketDataSubscriptionId (required).</param>
        public CancelSecondMarketDataSubscription(long? secondMarketDataSubscriptionId = default(long?))
        {
            // to ensure "secondMarketDataSubscriptionId" is required (not null)
            if (secondMarketDataSubscriptionId == null)
            {
                throw new InvalidDataException("secondMarketDataSubscriptionId is a required property for CancelSecondMarketDataSubscription and cannot be null");
            }
            else
            {
                this.SecondMarketDataSubscriptionId = secondMarketDataSubscriptionId;
            }
        }
        
        /// <summary>
        /// Gets or Sets SecondMarketDataSubscriptionId
        /// </summary>
        [DataMember(Name="secondMarketDataSubscriptionId", EmitDefaultValue=false)]
        public long? SecondMarketDataSubscriptionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancelSecondMarketDataSubscription {\n");
            sb.Append("  SecondMarketDataSubscriptionId: ").Append(SecondMarketDataSubscriptionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CancelSecondMarketDataSubscription);
        }

        /// <summary>
        /// Returns true if CancelSecondMarketDataSubscription instances are equal
        /// </summary>
        /// <param name="input">Instance of CancelSecondMarketDataSubscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancelSecondMarketDataSubscription input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SecondMarketDataSubscriptionId == input.SecondMarketDataSubscriptionId ||
                    (this.SecondMarketDataSubscriptionId != null &&
                    this.SecondMarketDataSubscriptionId.Equals(input.SecondMarketDataSubscriptionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SecondMarketDataSubscriptionId != null)
                    hashCode = hashCode * 59 + this.SecondMarketDataSubscriptionId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
