/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// CheckReplaySession
    /// </summary>
    [DataContract]
        public partial class CheckReplaySession :  IEquatable<CheckReplaySession>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckReplaySession" /> class.
        /// </summary>
        /// <param name="startTimestamp">startTimestamp (required).</param>
        public CheckReplaySession(DateTime? startTimestamp = default(DateTime?))
        {
            // to ensure "startTimestamp" is required (not null)
            if (startTimestamp == null)
            {
                throw new InvalidDataException("startTimestamp is a required property for CheckReplaySession and cannot be null");
            }
            else
            {
                this.StartTimestamp = startTimestamp;
            }
        }
        
        /// <summary>
        /// Gets or Sets StartTimestamp
        /// </summary>
        [DataMember(Name="startTimestamp", EmitDefaultValue=false)]
        public DateTime? StartTimestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CheckReplaySession {\n");
            sb.Append("  StartTimestamp: ").Append(StartTimestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CheckReplaySession);
        }

        /// <summary>
        /// Returns true if CheckReplaySession instances are equal
        /// </summary>
        /// <param name="input">Instance of CheckReplaySession to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CheckReplaySession input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StartTimestamp == input.StartTimestamp ||
                    (this.StartTimestamp != null &&
                    this.StartTimestamp.Equals(input.StartTimestamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartTimestamp != null)
                    hashCode = hashCode * 59 + this.StartTimestamp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
