/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// MarkReadAlertSignal
    /// </summary>
    [DataContract]
        public partial class MarkReadAlertSignal :  IEquatable<MarkReadAlertSignal>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkReadAlertSignal" /> class.
        /// </summary>
        /// <param name="alertId">alertId (required).</param>
        /// <param name="alertSignalId">alertSignalId (required).</param>
        public MarkReadAlertSignal(long? alertId = default(long?), long? alertSignalId = default(long?))
        {
            // to ensure "alertId" is required (not null)
            if (alertId == null)
            {
                throw new InvalidDataException("alertId is a required property for MarkReadAlertSignal and cannot be null");
            }
            else
            {
                this.AlertId = alertId;
            }
            // to ensure "alertSignalId" is required (not null)
            if (alertSignalId == null)
            {
                throw new InvalidDataException("alertSignalId is a required property for MarkReadAlertSignal and cannot be null");
            }
            else
            {
                this.AlertSignalId = alertSignalId;
            }
        }
        
        /// <summary>
        /// Gets or Sets AlertId
        /// </summary>
        [DataMember(Name="alertId", EmitDefaultValue=false)]
        public long? AlertId { get; set; }

        /// <summary>
        /// Gets or Sets AlertSignalId
        /// </summary>
        [DataMember(Name="alertSignalId", EmitDefaultValue=false)]
        public long? AlertSignalId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MarkReadAlertSignal {\n");
            sb.Append("  AlertId: ").Append(AlertId).Append("\n");
            sb.Append("  AlertSignalId: ").Append(AlertSignalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MarkReadAlertSignal);
        }

        /// <summary>
        /// Returns true if MarkReadAlertSignal instances are equal
        /// </summary>
        /// <param name="input">Instance of MarkReadAlertSignal to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarkReadAlertSignal input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AlertId == input.AlertId ||
                    (this.AlertId != null &&
                    this.AlertId.Equals(input.AlertId))
                ) && 
                (
                    this.AlertSignalId == input.AlertSignalId ||
                    (this.AlertSignalId != null &&
                    this.AlertSignalId.Equals(input.AlertSignalId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AlertId != null)
                    hashCode = hashCode * 59 + this.AlertId.GetHashCode();
                if (this.AlertSignalId != null)
                    hashCode = hashCode * 59 + this.AlertSignalId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
