/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// MarketDataSubscriptionPlan
    /// </summary>
    [DataContract]
        public partial class MarketDataSubscriptionPlan :  IEquatable<MarketDataSubscriptionPlan>, IValidatableObject
    {
        /// <summary>
        /// DOM, Top
        /// </summary>
        /// <value>DOM, Top</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum DataTypeEnum
        {
            /// <summary>
            /// Enum DOM for value: DOM
            /// </summary>
            [EnumMember(Value = "DOM")]
            DOM = 1,
            /// <summary>
            /// Enum Top for value: Top
            /// </summary>
            [EnumMember(Value = "Top")]
            Top = 2        }
        /// <summary>
        /// DOM, Top
        /// </summary>
        /// <value>DOM, Top</value>
        [DataMember(Name="dataType", EmitDefaultValue=false)]
        public DataTypeEnum DataType { get; set; }
        /// <summary>
        /// Either, NonProfessional, Professional
        /// </summary>
        /// <value>Either, NonProfessional, Professional</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ProfessionalEnum
        {
            /// <summary>
            /// Enum Either for value: Either
            /// </summary>
            [EnumMember(Value = "Either")]
            Either = 1,
            /// <summary>
            /// Enum NonProfessional for value: NonProfessional
            /// </summary>
            [EnumMember(Value = "NonProfessional")]
            NonProfessional = 2,
            /// <summary>
            /// Enum Professional for value: Professional
            /// </summary>
            [EnumMember(Value = "Professional")]
            Professional = 3        }
        /// <summary>
        /// Either, NonProfessional, Professional
        /// </summary>
        /// <value>Either, NonProfessional, Professional</value>
        [DataMember(Name="professional", EmitDefaultValue=false)]
        public ProfessionalEnum Professional { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketDataSubscriptionPlan" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="price">price (required).</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="discontinuedDate">discontinuedDate.</param>
        /// <param name="exchangeScopeId">exchangeScopeId (required).</param>
        /// <param name="dataType">DOM, Top (required).</param>
        /// <param name="professional">Either, NonProfessional, Professional (required).</param>
        /// <param name="tooltip">tooltip.</param>
        public MarketDataSubscriptionPlan(long? id = default(long?), string name = default(string), string title = default(string), double? price = default(double?), TradeDate startDate = default(TradeDate), TradeDate discontinuedDate = default(TradeDate), long? exchangeScopeId = default(long?), DataTypeEnum dataType = default(DataTypeEnum), ProfessionalEnum professional = default(ProfessionalEnum), string tooltip = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new InvalidDataException("title is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.Title = title;
            }
            // to ensure "price" is required (not null)
            if (price == null)
            {
                throw new InvalidDataException("price is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.Price = price;
            }
            // to ensure "exchangeScopeId" is required (not null)
            if (exchangeScopeId == null)
            {
                throw new InvalidDataException("exchangeScopeId is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.ExchangeScopeId = exchangeScopeId;
            }
            // to ensure "dataType" is required (not null)
            if (dataType == null)
            {
                throw new InvalidDataException("dataType is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.DataType = dataType;
            }
            // to ensure "professional" is required (not null)
            if (professional == null)
            {
                throw new InvalidDataException("professional is a required property for MarketDataSubscriptionPlan and cannot be null");
            }
            else
            {
                this.Professional = professional;
            }
            this.Id = id;
            this.StartDate = startDate;
            this.DiscontinuedDate = discontinuedDate;
            this.Tooltip = tooltip;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public double? Price { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [DataMember(Name="startDate", EmitDefaultValue=false)]
        public TradeDate StartDate { get; set; }

        /// <summary>
        /// Gets or Sets DiscontinuedDate
        /// </summary>
        [DataMember(Name="discontinuedDate", EmitDefaultValue=false)]
        public TradeDate DiscontinuedDate { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeScopeId
        /// </summary>
        [DataMember(Name="exchangeScopeId", EmitDefaultValue=false)]
        public long? ExchangeScopeId { get; set; }



        /// <summary>
        /// Gets or Sets Tooltip
        /// </summary>
        [DataMember(Name="tooltip", EmitDefaultValue=false)]
        public string Tooltip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MarketDataSubscriptionPlan {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  DiscontinuedDate: ").Append(DiscontinuedDate).Append("\n");
            sb.Append("  ExchangeScopeId: ").Append(ExchangeScopeId).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Professional: ").Append(Professional).Append("\n");
            sb.Append("  Tooltip: ").Append(Tooltip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MarketDataSubscriptionPlan);
        }

        /// <summary>
        /// Returns true if MarketDataSubscriptionPlan instances are equal
        /// </summary>
        /// <param name="input">Instance of MarketDataSubscriptionPlan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MarketDataSubscriptionPlan input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.DiscontinuedDate == input.DiscontinuedDate ||
                    (this.DiscontinuedDate != null &&
                    this.DiscontinuedDate.Equals(input.DiscontinuedDate))
                ) && 
                (
                    this.ExchangeScopeId == input.ExchangeScopeId ||
                    (this.ExchangeScopeId != null &&
                    this.ExchangeScopeId.Equals(input.ExchangeScopeId))
                ) && 
                (
                    this.DataType == input.DataType ||
                    (this.DataType != null &&
                    this.DataType.Equals(input.DataType))
                ) && 
                (
                    this.Professional == input.Professional ||
                    (this.Professional != null &&
                    this.Professional.Equals(input.Professional))
                ) && 
                (
                    this.Tooltip == input.Tooltip ||
                    (this.Tooltip != null &&
                    this.Tooltip.Equals(input.Tooltip))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.DiscontinuedDate != null)
                    hashCode = hashCode * 59 + this.DiscontinuedDate.GetHashCode();
                if (this.ExchangeScopeId != null)
                    hashCode = hashCode * 59 + this.ExchangeScopeId.GetHashCode();
                if (this.DataType != null)
                    hashCode = hashCode * 59 + this.DataType.GetHashCode();
                if (this.Professional != null)
                    hashCode = hashCode * 59 + this.Professional.GetHashCode();
                if (this.Tooltip != null)
                    hashCode = hashCode * 59 + this.Tooltip.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
