/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// ModifyOrderStrategy
    /// </summary>
    [DataContract]
        public partial class ModifyOrderStrategy :  IEquatable<ModifyOrderStrategy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyOrderStrategy" /> class.
        /// </summary>
        /// <param name="orderStrategyId">orderStrategyId (required).</param>
        /// <param name="command">command (required).</param>
        /// <param name="customTag50">customTag50.</param>
        public ModifyOrderStrategy(long? orderStrategyId = default(long?), string command = default(string), string customTag50 = default(string))
        {
            // to ensure "orderStrategyId" is required (not null)
            if (orderStrategyId == null)
            {
                throw new InvalidDataException("orderStrategyId is a required property for ModifyOrderStrategy and cannot be null");
            }
            else
            {
                this.OrderStrategyId = orderStrategyId;
            }
            // to ensure "command" is required (not null)
            if (command == null)
            {
                throw new InvalidDataException("command is a required property for ModifyOrderStrategy and cannot be null");
            }
            else
            {
                this.Command = command;
            }
            this.CustomTag50 = customTag50;
        }
        
        /// <summary>
        /// Gets or Sets OrderStrategyId
        /// </summary>
        [DataMember(Name="orderStrategyId", EmitDefaultValue=false)]
        public long? OrderStrategyId { get; set; }

        /// <summary>
        /// Gets or Sets Command
        /// </summary>
        [DataMember(Name="command", EmitDefaultValue=false)]
        public string Command { get; set; }

        /// <summary>
        /// Gets or Sets CustomTag50
        /// </summary>
        [DataMember(Name="customTag50", EmitDefaultValue=false)]
        public string CustomTag50 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifyOrderStrategy {\n");
            sb.Append("  OrderStrategyId: ").Append(OrderStrategyId).Append("\n");
            sb.Append("  Command: ").Append(Command).Append("\n");
            sb.Append("  CustomTag50: ").Append(CustomTag50).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModifyOrderStrategy);
        }

        /// <summary>
        /// Returns true if ModifyOrderStrategy instances are equal
        /// </summary>
        /// <param name="input">Instance of ModifyOrderStrategy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifyOrderStrategy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderStrategyId == input.OrderStrategyId ||
                    (this.OrderStrategyId != null &&
                    this.OrderStrategyId.Equals(input.OrderStrategyId))
                ) && 
                (
                    this.Command == input.Command ||
                    (this.Command != null &&
                    this.Command.Equals(input.Command))
                ) && 
                (
                    this.CustomTag50 == input.CustomTag50 ||
                    (this.CustomTag50 != null &&
                    this.CustomTag50.Equals(input.CustomTag50))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderStrategyId != null)
                    hashCode = hashCode * 59 + this.OrderStrategyId.GetHashCode();
                if (this.Command != null)
                    hashCode = hashCode * 59 + this.Command.GetHashCode();
                if (this.CustomTag50 != null)
                    hashCode = hashCode * 59 + this.CustomTag50.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
