/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// ProductMargin
    /// </summary>
    [DataContract]
        public partial class ProductMargin :  IEquatable<ProductMargin>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductMargin" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="initialMargin">initialMargin (required).</param>
        /// <param name="maintenanceMargin">maintenanceMargin (required).</param>
        /// <param name="timestamp">timestamp (required).</param>
        public ProductMargin(long? id = default(long?), double? initialMargin = default(double?), double? maintenanceMargin = default(double?), DateTime? timestamp = default(DateTime?))
        {
            // to ensure "initialMargin" is required (not null)
            if (initialMargin == null)
            {
                throw new InvalidDataException("initialMargin is a required property for ProductMargin and cannot be null");
            }
            else
            {
                this.InitialMargin = initialMargin;
            }
            // to ensure "maintenanceMargin" is required (not null)
            if (maintenanceMargin == null)
            {
                throw new InvalidDataException("maintenanceMargin is a required property for ProductMargin and cannot be null");
            }
            else
            {
                this.MaintenanceMargin = maintenanceMargin;
            }
            // to ensure "timestamp" is required (not null)
            if (timestamp == null)
            {
                throw new InvalidDataException("timestamp is a required property for ProductMargin and cannot be null");
            }
            else
            {
                this.Timestamp = timestamp;
            }
            this.Id = id;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets InitialMargin
        /// </summary>
        [DataMember(Name="initialMargin", EmitDefaultValue=false)]
        public double? InitialMargin { get; set; }

        /// <summary>
        /// Gets or Sets MaintenanceMargin
        /// </summary>
        [DataMember(Name="maintenanceMargin", EmitDefaultValue=false)]
        public double? MaintenanceMargin { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductMargin {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InitialMargin: ").Append(InitialMargin).Append("\n");
            sb.Append("  MaintenanceMargin: ").Append(MaintenanceMargin).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductMargin);
        }

        /// <summary>
        /// Returns true if ProductMargin instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductMargin to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductMargin input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.InitialMargin == input.InitialMargin ||
                    (this.InitialMargin != null &&
                    this.InitialMargin.Equals(input.InitialMargin))
                ) && 
                (
                    this.MaintenanceMargin == input.MaintenanceMargin ||
                    (this.MaintenanceMargin != null &&
                    this.MaintenanceMargin.Equals(input.MaintenanceMargin))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.InitialMargin != null)
                    hashCode = hashCode * 59 + this.InitialMargin.GetHashCode();
                if (this.MaintenanceMargin != null)
                    hashCode = hashCode * 59 + this.MaintenanceMargin.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
