/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// RollContract
    /// </summary>
    [DataContract]
        public partial class RollContract :  IEquatable<RollContract>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RollContract" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="forward">forward (required).</param>
        /// <param name="ifExpired">ifExpired.</param>
        public RollContract(string name = default(string), bool? forward = default(bool?), bool? ifExpired = default(bool?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for RollContract and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "forward" is required (not null)
            if (forward == null)
            {
                throw new InvalidDataException("forward is a required property for RollContract and cannot be null");
            }
            else
            {
                this.Forward = forward;
            }
            this.IfExpired = ifExpired;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Forward
        /// </summary>
        [DataMember(Name="forward", EmitDefaultValue=false)]
        public bool? Forward { get; set; }

        /// <summary>
        /// Gets or Sets IfExpired
        /// </summary>
        [DataMember(Name="ifExpired", EmitDefaultValue=false)]
        public bool? IfExpired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RollContract {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Forward: ").Append(Forward).Append("\n");
            sb.Append("  IfExpired: ").Append(IfExpired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RollContract);
        }

        /// <summary>
        /// Returns true if RollContract instances are equal
        /// </summary>
        /// <param name="input">Instance of RollContract to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RollContract input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Forward == input.Forward ||
                    (this.Forward != null &&
                    this.Forward.Equals(input.Forward))
                ) && 
                (
                    this.IfExpired == input.IfExpired ||
                    (this.IfExpired != null &&
                    this.IfExpired.Equals(input.IfExpired))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Forward != null)
                    hashCode = hashCode * 59 + this.Forward.GetHashCode();
                if (this.IfExpired != null)
                    hashCode = hashCode * 59 + this.IfExpired.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
