/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tradovate.Services.Client.SwaggerDateConverter;

namespace Tradovate.Services.Model
{
    /// <summary>
    /// UserAccountPositionLimit
    /// </summary>
    [DataContract]
        public partial class UserAccountPositionLimit :  IEquatable<UserAccountPositionLimit>, IValidatableObject
    {
        /// <summary>
        /// CommonStock, Continuous, Cryptocurrency, Futures, MarketInternals, Options, Spread
        /// </summary>
        /// <value>CommonStock, Continuous, Cryptocurrency, Futures, MarketInternals, Options, Spread</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ProductTypeEnum
        {
            /// <summary>
            /// Enum CommonStock for value: CommonStock
            /// </summary>
            [EnumMember(Value = "CommonStock")]
            CommonStock = 1,
            /// <summary>
            /// Enum Continuous for value: Continuous
            /// </summary>
            [EnumMember(Value = "Continuous")]
            Continuous = 2,
            /// <summary>
            /// Enum Cryptocurrency for value: Cryptocurrency
            /// </summary>
            [EnumMember(Value = "Cryptocurrency")]
            Cryptocurrency = 3,
            /// <summary>
            /// Enum Futures for value: Futures
            /// </summary>
            [EnumMember(Value = "Futures")]
            Futures = 4,
            /// <summary>
            /// Enum MarketInternals for value: MarketInternals
            /// </summary>
            [EnumMember(Value = "MarketInternals")]
            MarketInternals = 5,
            /// <summary>
            /// Enum Options for value: Options
            /// </summary>
            [EnumMember(Value = "Options")]
            Options = 6,
            /// <summary>
            /// Enum Spread for value: Spread
            /// </summary>
            [EnumMember(Value = "Spread")]
            Spread = 7        }
        /// <summary>
        /// CommonStock, Continuous, Cryptocurrency, Futures, MarketInternals, Options, Spread
        /// </summary>
        /// <value>CommonStock, Continuous, Cryptocurrency, Futures, MarketInternals, Options, Spread</value>
        [DataMember(Name="productType", EmitDefaultValue=false)]
        public ProductTypeEnum? ProductType { get; set; }
        /// <summary>
        /// Inactive, Locked, ReadyForContracts, ReadyToTrade, Verified
        /// </summary>
        /// <value>Inactive, Locked, ReadyForContracts, ReadyToTrade, Verified</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ProductVerificationStatusEnum
        {
            /// <summary>
            /// Enum Inactive for value: Inactive
            /// </summary>
            [EnumMember(Value = "Inactive")]
            Inactive = 1,
            /// <summary>
            /// Enum Locked for value: Locked
            /// </summary>
            [EnumMember(Value = "Locked")]
            Locked = 2,
            /// <summary>
            /// Enum ReadyForContracts for value: ReadyForContracts
            /// </summary>
            [EnumMember(Value = "ReadyForContracts")]
            ReadyForContracts = 3,
            /// <summary>
            /// Enum ReadyToTrade for value: ReadyToTrade
            /// </summary>
            [EnumMember(Value = "ReadyToTrade")]
            ReadyToTrade = 4,
            /// <summary>
            /// Enum Verified for value: Verified
            /// </summary>
            [EnumMember(Value = "Verified")]
            Verified = 5        }
        /// <summary>
        /// Inactive, Locked, ReadyForContracts, ReadyToTrade, Verified
        /// </summary>
        /// <value>Inactive, Locked, ReadyForContracts, ReadyToTrade, Verified</value>
        [DataMember(Name="productVerificationStatus", EmitDefaultValue=false)]
        public ProductVerificationStatusEnum? ProductVerificationStatus { get; set; }
        /// <summary>
        /// Contract, ContractGroup, DiscountGroup, Exchange, Overall, Product, ProductType
        /// </summary>
        /// <value>Contract, ContractGroup, DiscountGroup, Exchange, Overall, Product, ProductType</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TotalByEnum
        {
            /// <summary>
            /// Enum Contract for value: Contract
            /// </summary>
            [EnumMember(Value = "Contract")]
            Contract = 1,
            /// <summary>
            /// Enum ContractGroup for value: ContractGroup
            /// </summary>
            [EnumMember(Value = "ContractGroup")]
            ContractGroup = 2,
            /// <summary>
            /// Enum DiscountGroup for value: DiscountGroup
            /// </summary>
            [EnumMember(Value = "DiscountGroup")]
            DiscountGroup = 3,
            /// <summary>
            /// Enum Exchange for value: Exchange
            /// </summary>
            [EnumMember(Value = "Exchange")]
            Exchange = 4,
            /// <summary>
            /// Enum Overall for value: Overall
            /// </summary>
            [EnumMember(Value = "Overall")]
            Overall = 5,
            /// <summary>
            /// Enum Product for value: Product
            /// </summary>
            [EnumMember(Value = "Product")]
            Product = 6,
            /// <summary>
            /// Enum ProductType for value: ProductType
            /// </summary>
            [EnumMember(Value = "ProductType")]
            ProductType = 7        }
        /// <summary>
        /// Contract, ContractGroup, DiscountGroup, Exchange, Overall, Product, ProductType
        /// </summary>
        /// <value>Contract, ContractGroup, DiscountGroup, Exchange, Overall, Product, ProductType</value>
        [DataMember(Name="totalBy", EmitDefaultValue=false)]
        public TotalByEnum TotalBy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserAccountPositionLimit" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="contractId">contractId.</param>
        /// <param name="productId">productId.</param>
        /// <param name="exchangeId">exchangeId.</param>
        /// <param name="productType">CommonStock, Continuous, Cryptocurrency, Futures, MarketInternals, Options, Spread.</param>
        /// <param name="riskDiscountContractGroupId">riskDiscountContractGroupId.</param>
        /// <param name="productVerificationStatus">Inactive, Locked, ReadyForContracts, ReadyToTrade, Verified.</param>
        /// <param name="contractGroupId">contractGroupId.</param>
        /// <param name="active">active (required).</param>
        /// <param name="riskTimePeriodId">riskTimePeriodId.</param>
        /// <param name="totalBy">Contract, ContractGroup, DiscountGroup, Exchange, Overall, Product, ProductType (required).</param>
        /// <param name="shortLimit">shortLimit.</param>
        /// <param name="longLimit">longLimit.</param>
        /// <param name="exposedLimit">exposedLimit.</param>
        /// <param name="description">description.</param>
        /// <param name="accountId">accountId (required).</param>
        public UserAccountPositionLimit(long? id = default(long?), long? contractId = default(long?), long? productId = default(long?), long? exchangeId = default(long?), ProductTypeEnum? productType = default(ProductTypeEnum?), long? riskDiscountContractGroupId = default(long?), ProductVerificationStatusEnum? productVerificationStatus = default(ProductVerificationStatusEnum?), long? contractGroupId = default(long?), bool? active = default(bool?), long? riskTimePeriodId = default(long?), TotalByEnum totalBy = default(TotalByEnum), int? shortLimit = default(int?), int? longLimit = default(int?), int? exposedLimit = default(int?), string description = default(string), long? accountId = default(long?))
        {
            // to ensure "active" is required (not null)
            if (active == null)
            {
                throw new InvalidDataException("active is a required property for UserAccountPositionLimit and cannot be null");
            }
            else
            {
                this.Active = active;
            }
            // to ensure "totalBy" is required (not null)
            if (totalBy == null)
            {
                throw new InvalidDataException("totalBy is a required property for UserAccountPositionLimit and cannot be null");
            }
            else
            {
                this.TotalBy = totalBy;
            }
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new InvalidDataException("accountId is a required property for UserAccountPositionLimit and cannot be null");
            }
            else
            {
                this.AccountId = accountId;
            }
            this.Id = id;
            this.ContractId = contractId;
            this.ProductId = productId;
            this.ExchangeId = exchangeId;
            this.ProductType = productType;
            this.RiskDiscountContractGroupId = riskDiscountContractGroupId;
            this.ProductVerificationStatus = productVerificationStatus;
            this.ContractGroupId = contractGroupId;
            this.RiskTimePeriodId = riskTimePeriodId;
            this.ShortLimit = shortLimit;
            this.LongLimit = longLimit;
            this.ExposedLimit = exposedLimit;
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets ContractId
        /// </summary>
        [DataMember(Name="contractId", EmitDefaultValue=false)]
        public long? ContractId { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name="productId", EmitDefaultValue=false)]
        public long? ProductId { get; set; }

        /// <summary>
        /// Gets or Sets ExchangeId
        /// </summary>
        [DataMember(Name="exchangeId", EmitDefaultValue=false)]
        public long? ExchangeId { get; set; }


        /// <summary>
        /// Gets or Sets RiskDiscountContractGroupId
        /// </summary>
        [DataMember(Name="riskDiscountContractGroupId", EmitDefaultValue=false)]
        public long? RiskDiscountContractGroupId { get; set; }


        /// <summary>
        /// Gets or Sets ContractGroupId
        /// </summary>
        [DataMember(Name="contractGroupId", EmitDefaultValue=false)]
        public long? ContractGroupId { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name="active", EmitDefaultValue=false)]
        public bool? Active { get; set; }

        /// <summary>
        /// Gets or Sets RiskTimePeriodId
        /// </summary>
        [DataMember(Name="riskTimePeriodId", EmitDefaultValue=false)]
        public long? RiskTimePeriodId { get; set; }


        /// <summary>
        /// Gets or Sets ShortLimit
        /// </summary>
        [DataMember(Name="shortLimit", EmitDefaultValue=false)]
        public int? ShortLimit { get; set; }

        /// <summary>
        /// Gets or Sets LongLimit
        /// </summary>
        [DataMember(Name="longLimit", EmitDefaultValue=false)]
        public int? LongLimit { get; set; }

        /// <summary>
        /// Gets or Sets ExposedLimit
        /// </summary>
        [DataMember(Name="exposedLimit", EmitDefaultValue=false)]
        public int? ExposedLimit { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name="accountId", EmitDefaultValue=false)]
        public long? AccountId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserAccountPositionLimit {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ContractId: ").Append(ContractId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  ExchangeId: ").Append(ExchangeId).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("  RiskDiscountContractGroupId: ").Append(RiskDiscountContractGroupId).Append("\n");
            sb.Append("  ProductVerificationStatus: ").Append(ProductVerificationStatus).Append("\n");
            sb.Append("  ContractGroupId: ").Append(ContractGroupId).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  RiskTimePeriodId: ").Append(RiskTimePeriodId).Append("\n");
            sb.Append("  TotalBy: ").Append(TotalBy).Append("\n");
            sb.Append("  ShortLimit: ").Append(ShortLimit).Append("\n");
            sb.Append("  LongLimit: ").Append(LongLimit).Append("\n");
            sb.Append("  ExposedLimit: ").Append(ExposedLimit).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserAccountPositionLimit);
        }

        /// <summary>
        /// Returns true if UserAccountPositionLimit instances are equal
        /// </summary>
        /// <param name="input">Instance of UserAccountPositionLimit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserAccountPositionLimit input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ContractId == input.ContractId ||
                    (this.ContractId != null &&
                    this.ContractId.Equals(input.ContractId))
                ) && 
                (
                    this.ProductId == input.ProductId ||
                    (this.ProductId != null &&
                    this.ProductId.Equals(input.ProductId))
                ) && 
                (
                    this.ExchangeId == input.ExchangeId ||
                    (this.ExchangeId != null &&
                    this.ExchangeId.Equals(input.ExchangeId))
                ) && 
                (
                    this.ProductType == input.ProductType ||
                    (this.ProductType != null &&
                    this.ProductType.Equals(input.ProductType))
                ) && 
                (
                    this.RiskDiscountContractGroupId == input.RiskDiscountContractGroupId ||
                    (this.RiskDiscountContractGroupId != null &&
                    this.RiskDiscountContractGroupId.Equals(input.RiskDiscountContractGroupId))
                ) && 
                (
                    this.ProductVerificationStatus == input.ProductVerificationStatus ||
                    (this.ProductVerificationStatus != null &&
                    this.ProductVerificationStatus.Equals(input.ProductVerificationStatus))
                ) && 
                (
                    this.ContractGroupId == input.ContractGroupId ||
                    (this.ContractGroupId != null &&
                    this.ContractGroupId.Equals(input.ContractGroupId))
                ) && 
                (
                    this.Active == input.Active ||
                    (this.Active != null &&
                    this.Active.Equals(input.Active))
                ) && 
                (
                    this.RiskTimePeriodId == input.RiskTimePeriodId ||
                    (this.RiskTimePeriodId != null &&
                    this.RiskTimePeriodId.Equals(input.RiskTimePeriodId))
                ) && 
                (
                    this.TotalBy == input.TotalBy ||
                    (this.TotalBy != null &&
                    this.TotalBy.Equals(input.TotalBy))
                ) && 
                (
                    this.ShortLimit == input.ShortLimit ||
                    (this.ShortLimit != null &&
                    this.ShortLimit.Equals(input.ShortLimit))
                ) && 
                (
                    this.LongLimit == input.LongLimit ||
                    (this.LongLimit != null &&
                    this.LongLimit.Equals(input.LongLimit))
                ) && 
                (
                    this.ExposedLimit == input.ExposedLimit ||
                    (this.ExposedLimit != null &&
                    this.ExposedLimit.Equals(input.ExposedLimit))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.AccountId == input.AccountId ||
                    (this.AccountId != null &&
                    this.AccountId.Equals(input.AccountId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ContractId != null)
                    hashCode = hashCode * 59 + this.ContractId.GetHashCode();
                if (this.ProductId != null)
                    hashCode = hashCode * 59 + this.ProductId.GetHashCode();
                if (this.ExchangeId != null)
                    hashCode = hashCode * 59 + this.ExchangeId.GetHashCode();
                if (this.ProductType != null)
                    hashCode = hashCode * 59 + this.ProductType.GetHashCode();
                if (this.RiskDiscountContractGroupId != null)
                    hashCode = hashCode * 59 + this.RiskDiscountContractGroupId.GetHashCode();
                if (this.ProductVerificationStatus != null)
                    hashCode = hashCode * 59 + this.ProductVerificationStatus.GetHashCode();
                if (this.ContractGroupId != null)
                    hashCode = hashCode * 59 + this.ContractGroupId.GetHashCode();
                if (this.Active != null)
                    hashCode = hashCode * 59 + this.Active.GetHashCode();
                if (this.RiskTimePeriodId != null)
                    hashCode = hashCode * 59 + this.RiskTimePeriodId.GetHashCode();
                if (this.TotalBy != null)
                    hashCode = hashCode * 59 + this.TotalBy.GetHashCode();
                if (this.ShortLimit != null)
                    hashCode = hashCode * 59 + this.ShortLimit.GetHashCode();
                if (this.LongLimit != null)
                    hashCode = hashCode * 59 + this.LongLimit.GetHashCode();
                if (this.ExposedLimit != null)
                    hashCode = hashCode * 59 + this.ExposedLimit.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.AccountId != null)
                    hashCode = hashCode * 59 + this.AccountId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
