/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing AcceptTradingPermission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AcceptTradingPermissionTests
    {
        // TODO uncomment below to declare an instance variable for AcceptTradingPermission
        //private AcceptTradingPermission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AcceptTradingPermission
            //instance = new AcceptTradingPermission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AcceptTradingPermission
        /// </summary>
        [Test]
        public void AcceptTradingPermissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AcceptTradingPermission
            //Assert.IsInstanceOfType<AcceptTradingPermission> (instance, "variable 'instance' is a AcceptTradingPermission");
        }


        /// <summary>
        /// Test the property 'TradingPermissionId'
        /// </summary>
        [Test]
        public void TradingPermissionIdTest()
        {
            // TODO unit test for the property 'TradingPermissionId'
        }

    }

}
