/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing AddMarketDataSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddMarketDataSubscriptionTests
    {
        // TODO uncomment below to declare an instance variable for AddMarketDataSubscription
        //private AddMarketDataSubscription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddMarketDataSubscription
            //instance = new AddMarketDataSubscription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddMarketDataSubscription
        /// </summary>
        [Test]
        public void AddMarketDataSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddMarketDataSubscription
            //Assert.IsInstanceOfType<AddMarketDataSubscription> (instance, "variable 'instance' is a AddMarketDataSubscription");
        }


        /// <summary>
        /// Test the property 'MarketDataSubscriptionPlanIds'
        /// </summary>
        [Test]
        public void MarketDataSubscriptionPlanIdsTest()
        {
            // TODO unit test for the property 'MarketDataSubscriptionPlanIds'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Test]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
