/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing CheckReplaySessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckReplaySessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for CheckReplaySessionResponse
        //private CheckReplaySessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckReplaySessionResponse
            //instance = new CheckReplaySessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckReplaySessionResponse
        /// </summary>
        [Test]
        public void CheckReplaySessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckReplaySessionResponse
            //Assert.IsInstanceOfType<CheckReplaySessionResponse> (instance, "variable 'instance' is a CheckReplaySessionResponse");
        }


        /// <summary>
        /// Test the property 'CheckStatus'
        /// </summary>
        [Test]
        public void CheckStatusTest()
        {
            // TODO unit test for the property 'CheckStatus'
        }
        /// <summary>
        /// Test the property 'StartTimestamp'
        /// </summary>
        [Test]
        public void StartTimestampTest()
        {
            // TODO unit test for the property 'StartTimestamp'
        }

    }

}
