/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing MarketDataSubscriptionExchangeScope
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketDataSubscriptionExchangeScopeTests
    {
        // TODO uncomment below to declare an instance variable for MarketDataSubscriptionExchangeScope
        //private MarketDataSubscriptionExchangeScope instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketDataSubscriptionExchangeScope
            //instance = new MarketDataSubscriptionExchangeScope();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketDataSubscriptionExchangeScope
        /// </summary>
        [Test]
        public void MarketDataSubscriptionExchangeScopeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketDataSubscriptionExchangeScope
            //Assert.IsInstanceOfType<MarketDataSubscriptionExchangeScope> (instance, "variable 'instance' is a MarketDataSubscriptionExchangeScope");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'BundleOf'
        /// </summary>
        [Test]
        public void BundleOfTest()
        {
            // TODO unit test for the property 'BundleOf'
        }

    }

}
