/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing RequestTradingPermission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestTradingPermissionTests
    {
        // TODO uncomment below to declare an instance variable for RequestTradingPermission
        //private RequestTradingPermission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequestTradingPermission
            //instance = new RequestTradingPermission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequestTradingPermission
        /// </summary>
        [Test]
        public void RequestTradingPermissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestTradingPermission
            //Assert.IsInstanceOfType<RequestTradingPermission> (instance, "variable 'instance' is a RequestTradingPermission");
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CtaContact'
        /// </summary>
        [Test]
        public void CtaContactTest()
        {
            // TODO unit test for the property 'CtaContact'
        }
        /// <summary>
        /// Test the property 'CtaEmail'
        /// </summary>
        [Test]
        public void CtaEmailTest()
        {
            // TODO unit test for the property 'CtaEmail'
        }

    }

}
