/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing TradeDate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TradeDateTests
    {
        // TODO uncomment below to declare an instance variable for TradeDate
        //private TradeDate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TradeDate
            //instance = new TradeDate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TradeDate
        /// </summary>
        [Test]
        public void TradeDateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TradeDate
            //Assert.IsInstanceOfType<TradeDate> (instance, "variable 'instance' is a TradeDate");
        }


        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Test]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

    }

}
