/* 
 * Tradovate API
 *
 * Tradovate API provides an access to the complete set of robust Tradovate functionality.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tradovate.Services.Api;
using Tradovate.Services.Model;
using Tradovate.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tradovate.Services.Test
{
    /// <summary>
    ///  Class for testing UserSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSessionTests
    {
        // TODO uncomment below to declare an instance variable for UserSession
        //private UserSession instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSession
            //instance = new UserSession();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSession
        /// </summary>
        [Test]
        public void UserSessionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSession
            //Assert.IsInstanceOfType<UserSession> (instance, "variable 'instance' is a UserSession");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Test]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }

    }

}
